language: node_js
node_js:
  - '0.10'
  - '0.12'
cache:
  directories:
  - node_modules
before_install:
  - npm i -g npm@^2.0.0
  - npm config set spin false --global
  - sudo apt-get install libgnome-keyring-dev
before_script:
  - npm prune
  - curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
after_failure:
  - python travis_after_all.py
  - export $(cat .to_export_back)
before_deploy:
  - rm -f travis_after_all.py .to_export_back
after_script:
  - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
env:
  global:
  - secure: Q5VaKCSXjYqkgf2fl5t+X8WksNBckCyAiWbjHee48DEsaM+fm4w5lfaosxR0E0azmPfzUbMkjChk7ACIUYzpIKvvx4MuV/3q61SS2eT1GxUWbEpnZr4dpfP8EuTLg3l+Ket+o44e22Npxta9nTHoFMPCiOPVveKtzuNaTpJ9YbQi4+wGm0dsa5SKVQ5Wk7CHUHK9S7/UyjVOhX8SB+qsNx8iruZU7h45XnqMole6SNud6opLBNL4eLuVN+fc2ahKOkeuzj921qcmbDEMO4Hi09KcwHVhjVdM6uZ4GAW7UZLL7dkKKhYrQr1HNi8V+4jY/AuNcZ0kYKzQRViY1s8VEbCnEVRifOSJNo7cRlbo3GJ+F6LFsFbAwg6Hysw+BTVxu2ujOniGal8iYzDR6g5SP5BhQE5dMLeKoOq6mOSukpf/fy4oinoMUdSsY2IdxxoBmtHnRk7WE1UH+2/Nm4waYqk8fHI+R5JGSsehOUK6miL9kIfH5hnlN0tU7EVSo1++xIkYr5k8XfHIZ48+/uI2zN/7ly38AmpJyEYZib20fd3ojeG7+41D4JEislGe3kg3mV6DGkeLPArE20c2UcGvTaR9ehnIY9ml8c96e1DkoeWINV06kmXPAEQOXzP3bkabMxu1pKw+TSnxKF0729SWMid+NC9qwZI/owmayspJ048=
deploy:
  provider: npm
  email: oss@ehealthafrica.org
  skip_cleanup: true
  api_key:
    secure: ova7lNAmPGGOsUNT/bv7GXMjYautoXO7xrce61GCxeu6/Id3NJduCY3Q1TB51ZJQNPzxjbK15S+cWTE1Ji5CSORatXd8x7HJ4kF7tNgir7B1/Bkq7ez1OW5xy+QQyDwR+dVPc/Z/YXcHS9jSlKIHfSq370Fhq52n9tCLvb1BLUApU9idAEih15g4NFEXRVFxx2pDKkUuhevDAJYEMq28auqT017uIHQAP2c32Z7SXpnutvkxU3uoktJvGsKJnEgwY0Q+vNhU7o7xPHfQ1Ze/xKFjTHXmwD9/i47ug5TS4X2EZU1BWjXn887abMttJrepIyEdMo0TsXcuiChn83WqCLpw1jSeIQEXolypFZkuNc/tz8DL0xVc9xjlNtH6XKc0XD6xr+6NlebAIReeQjv4f9pIZG4tL0gqto9F54OKuPpT+Wa3guCDYUe5OIwU33KgZ1rl3k1cRs44P2jlmQfO8n+h399FOr2iafW9Pr911nPwgQMxO/YfN0S1GOE1rogV9jM9RO6g1Fn0jcb5RVu83+wL3N6tWok7bCMS5jHFsYsbs5loqTBa5OUZopahwKqj2ajTFkLR6agfwkCPkdIXRhgp6R66Q8J0QRCXP+iqVYL8Zm8HWMl9t+aOP3b7oJekC089/PlRasR0H7zsooY96p6PcJiMqCfL8qt71hJNrSw=
  on:
    branch: master
    repo: eHealthAfrica/grunt-tx
    condition: "$BUILD_LEADER$BUILD_AGGREGATE_STATUS = YESothers_succeeded"
