language: node_js
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - g++-4.8
node_js:
  - '0.10'
  - '0.12'
  - iojs-v3
  - iojs-v2
  - iojs-v1
  - '4.0'
  - '4.1'
  - '4.2'
  - '5.0'
env:
  global:
    - CXX=g++-4.8
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@^3.0.0
  - npm i -g node-gyp-install
  - node-gyp-install
  - npm config set spin false --global
before_script:
  - npm prune
  - npm run build
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
